### ISSUE TITLE
النصوص بين --- مفروض ان لاتضهر في الرندر

### ISSUE THREAD

**Issue by salemkode** [imAbdelhadi/simplemde-rtl#2]
![image](https://user-images.githubusercontent.com/58360393/127965753-0b5a23b0-d7fb-40a1-af68-6fc691b28fbb.png)

**Comment by imAbdelhadi** [comment]
الإخفاء في ترميز ماركداون يكون عبر نمط comment وليس عبر الثلاث خطوط
يمكنك معاينة دليل https://www.markdownguide.org/
